#!/bin/bash
# Claude Harness - Session Initialization Script
# Project: subagent_test_env
# Generated by claude-harness

set -e

# Colors
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

HARNESS_DIR=".claude-harness"
CONFIG="$HARNESS_DIR/config.json"

echo ""
echo -e "${BLUE}=======================================================${NC}"
echo -e "${BLUE}  CLAUDE HARNESS - Session Initialization${NC}"
echo -e "${BLUE}  Project: subagent_test_env${NC}"
echo -e "${BLUE}=======================================================${NC}"
echo ""

# Check harness exists
if [[ ! -f "$CONFIG" ]]; then
    echo -e "${RED}ERROR: Harness not initialized. Run 'claude-harness init' first.${NC}"
    exit 1
fi

# 1. Git Status
echo -e "${YELLOW}[1/6] GIT STATUS${NC}"
if command -v git &> /dev/null && [[ -d ".git" ]]; then
    BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")
    PROTECTED_BRANCHES="main master"

    if [[ " $PROTECTED_BRANCHES " =~ " $BRANCH " ]]; then
        echo -e "${RED}  WARNING: On protected branch '$BRANCH'!${NC}"
        echo -e "${RED}  Create a feature branch before making changes.${NC}"
    else
        echo -e "${GREEN}  Branch: $BRANCH${NC}"
    fi

    # Check for uncommitted changes
    if [[ -n $(git status --porcelain 2>/dev/null) ]]; then
        echo -e "${YELLOW}  Uncommitted changes detected${NC}"
    fi
else
    echo -e "${YELLOW}  Git not available or not a repository${NC}"
fi
echo ""

# 2. Virtual Environment
echo -e "${YELLOW}[2/6] VIRTUAL ENVIRONMENT${NC}"
VENV_PATH="venv/bin/activate"
if [[ -f "$VENV_PATH" ]]; then
    source "$VENV_PATH" 2>/dev/null
    echo -e "${GREEN}  Activated: venv${NC}"
else
    echo -e "${RED}  Virtual environment not found at venv${NC}"
    echo -e "${YELLOW}  Run: python -m venv venv${NC}"
fi
echo ""

# 3. Application Status
echo -e "${YELLOW}[3/6] APPLICATION${NC}"
PORT=8000
HEALTH_URL="http://localhost:$PORT/health"

if curl -s "$HEALTH_URL" > /dev/null 2>&1; then
    echo -e "${GREEN}  App running on port $PORT${NC}"
    APP_RUNNING=true
else
    echo -e "${YELLOW}  App not running on port $PORT${NC}"
    APP_RUNNING=false

    # Offer to start
    read -p "  Start the application? (y/N) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        if [[ -f ".env" ]]; then
            export $(grep -v '^#' .env | xargs) 2>/dev/null
        fi
        echo -e "${YELLOW}  Starting: python main.py${NC}"
        nohup python main.py > /tmp/subagent_test_env.log 2>&1 &
        sleep 3

        if curl -s "$HEALTH_URL" > /dev/null 2>&1; then
            echo -e "${GREEN}  App started successfully${NC}"
        else
            echo -e "${RED}  Failed to start. Check /tmp/subagent_test_env.log${NC}"
        fi
    fi
fi
echo ""

# 4. Database (skip)
echo -e "${YELLOW}[4/6] DATABASE${NC}"
echo -e "${GREEN}  No database configured${NC}"
echo ""

# 5. Test Status
echo -e "${YELLOW}[5/6] TESTS${NC}"
if command -v pytest &> /dev/null; then
    UNIT_RESULT=$(pytest tests/unit/ -v --tb=no -q 2>&1 | tail -3)
    echo -e "  $UNIT_RESULT"
else
    echo -e "${YELLOW}  pytest not available${NC}"
fi
echo ""

# 6. Session Progress
echo -e "${YELLOW}[6/6] SESSION PROGRESS${NC}"
PROGRESS_FILE="$HARNESS_DIR/progress.md"
FEATURES_FILE="$HARNESS_DIR/features.json"

if [[ -f "$PROGRESS_FILE" ]]; then
    echo ""
    echo -e "${BLUE}--- Last Session Summary ---${NC}"
    # Show relevant sections from progress.md
    sed -n '/^## Last Session/,/^## Previous/p' "$PROGRESS_FILE" | head -25
    echo -e "${BLUE}----------------------------${NC}"
fi

if [[ -f "$FEATURES_FILE" ]] && command -v jq &> /dev/null; then
    echo ""
    CURRENT_PHASE=$(jq -r '.current_phase' "$FEATURES_FILE")
    echo -e "  Current Phase: ${GREEN}$CURRENT_PHASE${NC}"

    IN_PROGRESS=$(jq -r '.features[] | select(.status == "in_progress") | "\(.id): \(.name)"' "$FEATURES_FILE" 2>/dev/null | head -1)
    if [[ -n "$IN_PROGRESS" ]]; then
        echo -e "  In Progress: ${YELLOW}$IN_PROGRESS${NC}"
    else
        NEXT_PENDING=$(jq -r '.features[] | select(.status == "pending") | "\(.id): \(.name)"' "$FEATURES_FILE" 2>/dev/null | head -1)
        if [[ -n "$NEXT_PENDING" ]]; then
            echo -e "  Next Pending: ${BLUE}$NEXT_PENDING${NC}"
        fi
    fi
fi

echo ""
echo -e "${BLUE}}=======================================================${NC}"
echo -e "${GREEN}  Ready to work!${NC}"
echo -e "${BLUE}  Read .claude-harness/progress.md for full context${NC}"
echo -e "${BLUE}=======================================================${NC}"
echo ""
